Update yarn, better assets precompile on builder

diff --git a/builder/Dockerfile b/builder/Dockerfile
--- a/builder/Dockerfile
+++ b/builder/Dockerfile
@@ -1,3 +1,4 @@
+# syntax = docker/dockerfile:1.0-experimental
 FROM ruby:2.6.6-alpine
 LABEL maintainer="ian@i2w.me"
 
@@ -14,7 +15,7 @@ ENV APK_LIST build-base \
              tzdata \
              yarn 
 
-# Install edge repositories and our APK_LIST, cleanup 
+# Install edge repositories and our APK_LIST, cleanup
 RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories && \
     echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
     echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
@@ -35,29 +36,34 @@ RUN gem update bundler && \
     bundle config build.sassc --disable-march-tune-native && \
     bundle install -j4 --retry 3
 
-# Copy standard Docker/ dir, which contains:
-#   - empty Apkfile
-#   - install gems script 'bundle_install'
-#   - precompile assets script 'assets_precompile'
-# (these can be overridden by the child image)
-COPY Docker Docker
-
 ## ONBUILD triggers ##
 
-# Copy any Docker/* overrides (Apkfile(s), bundle_install, assets_precompile)
-ONBUILD COPY Docker/* Docker/
-
 # Install Apkfile packages listed in all Apkfile(s)
-ONBUILD RUN apk add --no-cache $(cat Docker/Apkfile* | xargs) && \
+ONBUILD RUN touch /app/Apkfile
+ONBUILD COPY Apkfile* /app/
+ONBUILD RUN apk add $(cat /app/Apkfile* | xargs) && \
             rm -rf /var/cache/* && mkdir /var/cache/apk
 
 # Install gem bundle 
 ONBUILD COPY Gemfile* /app/
-ONBUILD RUN Docker/bundle_install
+ONBUILD RUN bundle install -j4 --retry 3 &&\
+            bundle clean --force && \
+            rm -rf /usr/local/bundle/cache/*.gem && \
+            find /usr/local/bundle/gems/ -name "*.c" -delete && \
+            find /usr/local/bundle/gems/ -name "*.o" -delete
 
-# Precompile assets
-ONBUILD COPY app config Rakefile bin public /app/
-ONBUILD RUN Docker/assets_precompile
+# Copy files that affect assets, then precompile assets
+ONBUILD RUN $(cd /app; mkdir -p app/javascript app/assets config bin public vendor/assets)
+ONBUILD COPY package.json yarn.lock *.config.js Rakefile /app/
+ONBUILD COPY app/javascript               /app/app/javascript
+ONBUILD COPY app/assets                   /app/app/assets
+ONBUILD COPY bin                          /app/bin/
+ONBUILD COPY config                       /app/config/
+ONBUILD COPY public                       /app/public/
+ONBUILD COPY vendor/.keep vendor/assets*  /app/vendor/assets
+ONBUILD RUN mv config/credentials.yml.enc config/credentials.yml.enc.bak 2>/dev/null || true
+ONBUILD RUN RAILS_ENV=production SECRET_KEY_BASE=X RAILS_PRODUCTION_KEY=X bundle exec rails assets:precompile
+ONBUILD RUN mv config/credentials.yml.enc.bak config/credentials.yml.enc 2>/dev/null || true
 
-# Copy the whole application folder into the image
-ONBUILD COPY . /app
+# Copy the rest of the application into the image
+ONBUILD COPY . /app/
