Dockerfile updates

diff --git a/builder/Dockerfile b/builder/Dockerfile
--- a/builder/Dockerfile
+++ b/builder/Dockerfile
@@ -5,7 +5,8 @@ LABEL maintainer="ian@i2w.me"
 RUN apk add --no-cache \
         build-base \
         cmake \
-	postgresql-dev \
+	vips \
+        postgresql-dev \
         git \
         nodejs \
         yarn \
@@ -15,7 +16,7 @@ RUN apk add --no-cache \
 WORKDIR /app
 
 # Install standard Node modules
-COPY package.json yarn.lock* /app/
+COPY package.json* yarn.lock* /app/
 RUN yarn install --check-files
 
 # Install standard gems
@@ -24,12 +25,7 @@ RUN gem update bundler && \
     bundle config build.sassc --disable-march-tune-native && \
     bundle install -j4 --retry 3
 
-# ONBUILD triggers - when an image is built from this image 
-#   - install app gems, remove unneeded ones, and cleanup
-#   - install app assets (on top of the default yarn packages)
-#   - copy the application into place
-
-# Install all gems, and cleanup
+# Install app gems, and cleanup
 ONBUILD COPY Gemfile* /app/
 ONBUILD RUN bundle install -j4 --retry 3 && \
 	    bundle clean --force && \
@@ -37,14 +33,13 @@ ONBUILD RUN bundle install -j4 --retry 3 && \
             find /usr/local/bundle/gems/ -name "*.c" -delete && \
             find /usr/local/bundle/gems/ -name "*.o" -delete
 
-# Install assets
-# Notes: For an app using encrypted credentials, Rails raises a `MissingKeyError`
-#        if the master key is missing. Because on CI there is no master key,
-#        we hide the credentials while compiling assets.
-ONBUILD COPY package.json yarn.lock* /app/
-ONBUILD RUN mv config/credentials.yml.enc config/credentials.yml.enc.bak 2>/dev/null || true
-ONBUILD RUN bundle exec rails assets:precompile SECRET_KEY_BASE=X RAILS_MASTER_KEY=X 
-ONBUILD RUN mv config/credentials.yml.enc.bak config/credentials.yml.enc 2>/dev/null || true
-
 # Copy the whole application folder into the image
 ONBUILD COPY . /app
+
+# Install app assets modules. Note: we hide credentials while compiling
+ONBUILD RUN mv config/credentials.yml.enc config/credentials.yml.enc.bak 2>/dev/null || true
+ONBUILD RUN RAILS_ENV=production SECRET_KEY_BASE=X RAILS_MASTER_KEY=X \
+            bundle exec rails assets:precompile
+ONBUILD RUN mv config/credentials.yml.enc.bak config/credentials.yml.enc 2>/dev/null || true
+
+
